### ISSUE TITLE
Pozmieniano API Filmweba

### ISSUE THREAD

**Issue by gagyn** [nickofc/FilmWeb-API#11]
Coś zmieniono przy wysyłaniu requestów do API Filmweba, nie działa 90% funkcji.
Co ciekawe, niektóre filmy działają, a niektóre nie (rzuca wyjątek).
Co jeszcze ciekawsze testy ShouldGetFilmPerson przechodzą 2 na 9 - wszystkie są tego samego filmu.
Nie rozumiem co jest nie tak, może ktoś z was ma pojęcie? Mógłbym to poprawić, ale nie wiem jak
@nickofc @leszko11 
![image](https://user-images.githubusercontent.com/35143425/77792270-5d277c80-7068-11ea-8344-2bc6a4871fe2.png)

**Comment by leszko11** [comment]
Eh, czyli nie zdążyłem napisać swojej wersji 😅
Najciekawsza jest odpowiedź
`ok
err
13, Parameters don not seem to be in JSON format`

**Comment by nickofc** [comment]
Może backend im się sypie?

**Comment by leszko11** [comment]
Ja sprawdziłem dopiero po tym jak @gagyn napisał

**Comment by gagyn** [comment]
Chyba dzisiaj, ale mogło to być kilka dni temu

**Comment by gagyn** [comment]
Da się w jakiś sposób dojść do tego jak teraz działa to API? Nie za bardzo znam się na requestach, więc nie wiem od czego zacząć

**Comment by nickofc** [comment]
> Da się w jakiś sposób dojść do tego jak teraz działa to API? 
Nie, nie da się. 

> Dzisiaj, ale mogli to popsuć kilka dni temu
Może to po prostu piątkowy deploy albo kończą z tym API (aplikacji na telefon już nie mają)).

**Comment by gagyn** [comment]
To zobaczymy jak się rozwinie.
Nie rozumiem dlaczego, aż tak bardzo chronią tych swoich danych

**Comment by gagyn** [comment]
Ciekawe w sumie jest to, że dla np. Wiedźmina większość funkcji działa

**Comment by gagyn** [comment]
Stan na dzisiaj:
47 Passed
25 Failed
czyli 2/3 działa
I tak tutaj nic nie wymyślimy, więc zamykam ten issue
